python-gdb now catchs ``UnicodeDecodeError`` exceptions when calling
``string()``.
