Fix running ``python -m curses.has_key``.
